version: '3'

services:
  fabrikamfiber.web:
    image: fabrikamfiber.web:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\shmaniar\source\repos\fabrikam\2017\FabrikamFiber.Web:C:\inetpub\wwwroot
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\bin\\FabrikamFiber.Web.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"

